### ISSUE TITLE
Clarify in docs: publishing package publishes docs too

### ISSUE THREAD

**Issue by christhekeele** [ucwaldo/expublish#28]
This is a minor note; most people publishing packages are aware that `hex.publish` will publish to hexdocs too. But it might be nice to clarify closer to the publishing task docs, and would make the "Using mix expublish guarantees" section in the README sound even more comprehensive.

**Comment by ucwaldo** [comment]
Thanks @christhekeele i extended the list and noted that it's possible to opt out from some of the steps earlier in the readme.
Also added a headline hoping it'll make the initial text blob easier to read :)

Appreciate it the feedback!
