### ISSUE TITLE
ISO 8601 date formats in changelog

### ISSUE THREAD

**Issue by wojtekmach** [ucwaldo/expublish#40]
Currently we have e.g.:

    2.5.5 - 02. Mar 2021 19:21

I'd consider:

    2.5.5 - 2021-03-02

as that's what https://keepachangelog.com/en/1.0.0/ recommends and what we can easily parse from Elixir using `Date.from_iso8601!/1`. (I'd skip the hour/minute too, but of course including those is totally fine per ISO 8601)

**Comment by ucwaldo** [comment]
Glad about that suggestion, thanks for the feedback!
That'll dramatically loosen the elixir version requirement as I went with the new `Calendar.strftime/3` for obviously bad reasons 🤷 🙃 

I'll keep the hour/minute but will make it optional 👍
