### ISSUE TITLE
Failed commands do not return non-zero exist status

### ISSUE THREAD

**Issue by christhekeele** [ucwaldo/expublish#48]
:wave: Hey there!

I was setting up a new build with expublish, and tinkering with failure modes. I made a typo in my version file name, ex:

```sh
mix expublish.minor --version-file=VXRION
```

It took me a while to notice this, because it wasn't actually failing my CI builds!

<img width="672" alt="Screen Shot 2021-12-18 at 2 38 19 PM" src="https://user-images.githubusercontent.com/1406220/146653707-51a7bb94-80eb-47d4-8e1a-11eed3934b06.png">

As you can see, the build continued on since the `mix expublish` task did not actually fail according to bash semantics. Fortunately, I was running with `--disable-push` and it failed later; so I didn't have to fixup anything.

This seems Not Great™️ .

**Comment by ucwaldo** [comment]
:wave: Thanks for the valuable feedback @christhekeele
i'll make sure the task exits with proper exit codes and create a new release soon!

**Comment by christhekeele** [comment]
💞❤️🧡💛💚💙💜💖💜💙💚🧡💛❤️💘

**Comment by ucwaldo** [comment]
released expublish 2.7.2 with a fix for this. Let me know if you run into more trouble using the task!

**Comment by christhekeele** [comment]
Thanks!
